[package]
name = "oh-my-kiwi-tcp"
version = "0.1.0"
edition = "2024"

[dependencies]
oh-my-kiwi-domain = { path = "../oh-my-kiwi-domain" }
oh-my-kiwi-server = { path = "../oh-my-kiwi-server" }
tracing = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }

