[package]
name = "oh-my-kiwi-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
num-bigint = { workspace = true }
ordered-float = { workspace = true }
tokio = { workspace = true }