[package]
name = "oh-my-kiwi-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
oh-my-kiwi-domain = { path = "../oh-my-kiwi-domain" }
async-trait = { workspace = true }
tokio = { workspace = true }
